import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { activeSessionDirectory } from './directSession.ts'

const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const api = readFileSync(new URL('./api.ts', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('./i18n.ts', import.meta.url), 'utf8')
const styles = readFileSync(new URL('./styles.css', import.meta.url), 'utf8')

const selectedSession = Object.freeze({ id: 'session-1', directory: '/sessions/immutable' })
/** @type {string} */
const typedDraftDirectory = '/draft/manual-entry'

assert.equal(activeSessionDirectory(selectedSession), '/sessions/immutable', 'selected session should keep its immutable directory')
assert.equal(activeSessionDirectory(null), undefined, 'no selected session should have no active directory')
assert.equal(activeSessionDirectory(undefined), undefined, `typed draft ${typedDraftDirectory} must not become the active directory`)
assert.equal(activeSessionDirectory.length, 1, 'draft directory must not be accepted by the active-session API')

const defaultOptionLoaders = app.slice(app.indexOf('  async function loadAgents()'), app.indexOf('  async function loadSessionActivityTimes('))
assert.ok(defaultOptionLoaders.includes('api.listAgents(config, activeSessionDirectory(selectedSession))'), 'default agent requests should use only the selected session directory')
assert.ok(defaultOptionLoaders.includes('directory = activeSessionDirectory(selectedSession)'), 'default model requests should use only the selected session directory')
assert.ok(!defaultOptionLoaders.includes('selectedNewSessionDirectory'), 'manual draft directory must not leak into default model or agent requests')

assert.ok(api.includes('listModels(config: ServerConfig'), 'API should expose configured OpenCode models')
assert.ok(api.includes('withDirectory("/config/providers"'), 'model list should use official /config/providers with directory scoping')
assert.ok(api.includes('`/session/${sessionID}/prompt_async`'), 'chat prompts should use OpenCode async prompt endpoint')
assert.ok(api.includes('return request<boolean>(config, withDirectory(`/session/${sessionID}/prompt_async`, directory)'), 'async prompt should return after 204 instead of waiting for assistant output')
assert.ok(api.includes('model: toModelBody(model)'), 'prompt requests should send selected model object')
assert.ok(api.includes('variant: model?.variant || undefined'), 'prompt requests should preserve selected model variant')
assert.ok(api.includes('agent: agentID'), 'prompt requests should send the selected primary agent')
assert.ok(api.includes('listAgents(config: ServerConfig'), 'API should expose configured OpenCode agents')
assert.ok(api.includes('withDirectory("/agent"'), 'agent list should use official /agent endpoint with directory scoping')
assert.ok(api.includes('toCreateSessionModel'), 'new sessions should be creatable with the selected model')
assert.ok(app.includes('MODEL_STORAGE_KEY'), 'selected AI model should persist locally')
assert.ok(app.includes('AGENT_STORAGE_KEY'), 'selected plan/build agent should persist locally')
assert.ok(app.includes('modelStorageScope(backend: ServerConfig["backend"], sessionID?: string)'), 'model persistence must be scoped by backend and session')
assert.ok(app.includes('writeStoredModel(config.backend, selectedSession?.id, nextKey)'), 'model changes must persist only for the open backend session')
assert.ok(/const activeModel = activeModelOption[\s\S]*?: undefined/.test(app), 'a prompt must never send a stored model that is absent from the current backend catalog')
assert.ok(app.includes('loadModelsRequestRef'), 'stale model catalogs from another session or backend must be ignored')
assert.ok(app.includes('if (requestID !== loadModelsRequestRef.current) return'), 'only the latest model request may update the picker')
assert.ok(app.includes('agentOptions.filter((agent) => agent.mode === "primary" || agent.mode === "all")'), 'agent picker should expose primary agents such as build and plan')
assert.ok(app.includes('activeAgent?.id ?? "build"'), 'agent selection should default to build')
assert.ok(app.includes('id="agent-select"'), 'AI sheet should render an agent selector')
assert.ok(app.includes('api.sendPrompt(config, selectedSession.id, text, selectedSession.directory, activeModel, activeAgentID)'), 'chat prompts should use selected agent')
assert.ok(app.includes('api.sendCommand(config, selectedSession.id, command, args, selectedSession.directory, activeModel, activeAgentID)'), 'slash commands should use selected agent')
assert.ok(app.includes('session-context-strip'), 'detail UX should expose compact mobile context chips')
assert.ok(app.includes('activeDetailSheet === "ai"'), 'model picker should open in the bottom sheet')
assert.ok(app.includes("t('detail.modelHint')"), 'model picker should explain when the change applies')
assert.ok(app.includes('disabled={isWorking}'), 'model picker should be disabled while a session is running')
assert.ok(app.includes('modelSearchText'), 'model picker should support searching models')
assert.ok(app.includes('id="model-search"'), 'model picker should render a searchable model input')
assert.ok(app.includes("api.createSession(config, t('sessions.remoteSessionTitle'), activeModel, directory)"), 'new sessions should inherit the selected model and use a translated remote title')
assert.ok(app.includes('diffFiles.length > 0 ? t(\'detail.filesCount\''), 'details sheet should summarize file diffs only when diff data exists')
assert.ok(!app.includes('showFilesChip = diffFiles.length > 0'), 'file diff chip should stay removed from the context strip')
assert.ok(i18n.includes("'detail.contextStripLabel'"), 'context chip strings should be translated')
assert.ok(i18n.includes("'detail.modelToolsYes'"), 'model capability text should be translated')
assert.ok(i18n.includes("'detail.modelSearchPlaceholder'"), 'model search strings should be translated')
assert.ok(/\.context-chip[\s\S]*?overflow/.test(styles), 'context chips should have compact mobile styling')
assert.ok(/\.bottom-sheet[\s\S]*?max-height/.test(styles), 'model/details should use a mobile bottom sheet')
assert.ok(/\.model-option-list[\s\S]*?overflow-y/.test(styles), 'searchable model results should scroll in the sheet')
assert.ok(/\.model-option[\s\S]*?min-height:\s*64px/.test(styles), 'model options should be tall enough for two-line labels')
assert.ok(/\.model-option span[\s\S]*?line-height:\s*1\.25/.test(styles), 'model option text should not look vertically squeezed')

console.log('model picker regression tests passed')
